spring.application.name=order-service-v1

spring.datasource.url=jdbc:postgresql://localhost:5432/order_service_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# 1. Endereço do Cluster Kafka (porta mapeada no docker-compose)
spring.kafka.bootstrap-servers=localhost:9092

# Configurações do Producer (Envio de DTO para JSON)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Configurações do Consumer (Receção de JSON para DTO)
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Segurança e Confiança para o Jackson ler o DTO
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${AWS_ACCESS_SECRET_KEY}
spring.cloud.aws.region.static=us-east-2
aws.s3.bucket.name=notes-order-service-kayk

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
